version: '3.8'

services:
  backend:
    build:
      context: ./Backend
    container_name: backend_service
    ports:
      - "5001:5001"  # Host:Container
    volumes:
      - ./Backend:/app  # <-- Mount the backend folder
    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend
    container_name: frontend_service
    ports:
      - "5000:5000"  # Frontend exposed on host
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5001
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
