apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: himanshu9271/backend:latest
          ports:
            - containerPort: 5001
          env:
            - name: DATA_PATH
              value: "/app/data/dataset.csv"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5001
            initialDelaySeconds: 200
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5001
            initialDelaySeconds: 220
            periodSeconds: 20
            failureThreshold: 3
