- name: Install Metrics Server
  ansible.builtin.shell: |
    export KUBECONFIG={{ kubeconfig_path }}
    kubectl apply -f /tmp/components.yaml
  args:
    executable: /bin/bash

- name: Wait for Metrics Server to be Ready
  ansible.builtin.shell: |
    export KUBECONFIG={{ kubeconfig_path }}
    kubectl rollout status deployment/metrics-server -n kube-system --timeout=120s
  register: metrics_status
  changed_when: "'successfully rolled out' in metrics_status.stdout"
  args:
    executable: /bin/bash

- name: Apply HPA Configuration
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    definition: "{{ lookup('file', k8s_path + '/hpa.yaml') }}"
